#!/usr/bin/env python3
"""Self-evolution tools (PRD §19): explore a module, list what has been learned.

`explore_module.py` writes its output next to its own source — `REF_DIR =
<package>/references`. Installed from a wheel that resolves under
`site-packages`, which is read-only on most systems, so generation would crash
exactly where this feature is supposed to shine. This module therefore
**reassigns the script's public module global** to a writable per-user
directory. The script itself is never edited: it is verified against a live
instance and this server is only a wrapper around it.

**Importing this module redirects `explore_module.REF_DIR`** — the call at the
bottom of the file runs on import, so anything that imports the script
afterwards *by the same name* sees the user path. That name is the
package-qualified one; see the import below. `register()` re-applies it, so
the redirect holds whichever way this module is reached. Neither creates the
directory: `mkdir` happens only when a reference is actually written, exactly
where `explore_module.main()` does it. Importing the server must not touch the
user's disk.
"""
import contextlib
import io
import re
from pathlib import Path

from mcp.server import MCPServer

from odoo_assistant import server
# Package-qualified, unlike the bare bootstrap the sibling modules use: a bare
# `import explore_module` loads the same file under a SECOND `sys.modules` key,
# and the redirect below would then be invisible to every qualified importer.
from odoo_assistant.odoo_scripts import explore_module as explorer
from odoo_assistant.server_errors import (
    ToolOutcome,
    handle_odoo_exception,
    tool_result,
)

# Mirrors the ceiling `explore_module.main()` applies to a generated body. It
# is a local there, so it cannot be imported — a reference the agent cannot
# afford to open is worse than none, because it gets skipped and the agent
# guesses instead.
REFERENCE_SIZE_LIMIT = 12 * 1024

_GENERATED_ON = re.compile(r"^> Generated by `explore_module\.py \S+` on (\S+ \S+) against", re.M)
_VOLUME_ROW = re.compile(r"^\| `[\w.]+` \| (\d+) \|", re.M)


def _redirect_references() -> str:
    """Point the script's output at a writable per-user directory."""
    explorer.REF_DIR = str(Path.home() / ".local" / "share" / "odoo-assistant" / "references")
    return explorer.REF_DIR


def _bundled_references() -> Path:
    """The read-only reference set shipped with the package.

    Hatch force-includes `references_public/` as `odoo_assistant/references`;
    in a source checkout only the former exists.
    """
    installed = Path(__file__).parent / "references"
    if installed.is_dir():
        return installed
    return Path(__file__).resolve().parents[2] / "references_public"


def explore_module(module_name: str, action: str = "list", models: str = "") -> str:
    """Discover a module's structure by interrogating the live instance.

    Args:
        module_name: Module to explore, e.g. "helpdesk". Names the reference
            file on "generate"; ignored on "list".
        action: "list" ranks what is worth exploring, "generate" writes the
            reference document.
        models: Comma-separated models for a module the script does not know,
            e.g. "superchat.message,superchat.template". Defaults to the
            script's own grouping for `module_name`.
    """
    try:
        outcome = _explore(module_name, action, models)
    except Exception as exc:
        outcome = handle_odoo_exception(exc)
    return outcome.deliver()


def list_known_modules() -> str:
    """List the modules this server has learned: name, generation date, records."""
    return tool_result(
        _scan(_bundled_references(), "bundled")
        + _scan(Path(explorer.REF_DIR), "generated")
    )


def register(mcp: MCPServer) -> None:
    """Attach the self-evolution tools and re-assert the reference redirect."""
    _redirect_references()
    mcp.tool()(explore_module)
    mcp.tool()(list_known_modules)


def _explore(module_name: str, action: str, models: str) -> ToolOutcome:
    odoo = server._get_odoo()
    ctx = {"allowed_company_ids": explorer.companies(odoo)}
    match action:
        case "list":
            # The script prints its ranking; on stdio transport stdout carries
            # the JSON-RPC stream and nothing else, so capture it.
            buffer = io.StringIO()
            with contextlib.redirect_stdout(buffer):
                explorer.cmd_list(odoo, ctx)
            return ToolOutcome(False, tool_result(buffer.getvalue()))
        case "generate":
            return _generate(odoo, module_name, models, ctx)
        case _:
            return ToolOutcome(
                True, f"Unknown action {action!r}. Use 'list' or 'generate'."
            )


def _generate(odoo: object, name: str, models: str, ctx: dict) -> ToolOutcome:
    wanted = [m.strip() for m in models.split(",") if m.strip()] or explorer.KNOWN.get(name)
    if not wanted:
        return ToolOutcome(
            True,
            f"Unknown module {name!r}. Either name one of: "
            + ", ".join(sorted(explorer.KNOWN))
            + " — or pass models=\"a.b,c.d\" to explore any module, including "
            "an in-house one.",
        )

    body = explorer.generate(odoo, name, wanted, ctx)
    if len(body) > REFERENCE_SIZE_LIMIT:
        return ToolOutcome(True, _over_budget(name, body))

    directory = Path(explorer.REF_DIR)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"{name}.md"
    # Two-half write: the body ends at the NOTES marker, hand-written notes
    # below it are carried over from the previous generation.
    path.write_text(body + explorer.preserved_notes(str(path)))
    return ToolOutcome(
        False,
        f"Written: {path} ({path.stat().st_size / 1024:.1f} KB). "
        f"The NOTES section at the bottom was preserved.",
    )


def _over_budget(name: str, body: str) -> str:
    """Refusal text naming the sections that blew the budget."""
    largest = sorted(re.split(r"\n(?=### )", body), key=len, reverse=True)[:2]
    sections = "\n".join(
        f"  largest section: {len(s) / 1024:.1f} KB — {s.splitlines()[0][:60]}"
        for s in largest
    )
    return (
        f"REFUSED: the reference for {name!r} came out at {len(body) / 1024:.1f} KB, over "
        f"the {REFERENCE_SIZE_LIMIT / 1024:.0f} KB budget, so nothing was written. A "
        f"reference this large will not be loaded. Usually a lookup table was "
        f"mistaken for a workflow, or too many models were passed at once.\n"
        f"{sections}\n"
        f'Re-run with fewer models: explore_module("{name}", "generate", models="a.b").'
    )


def _scan(directory: Path, source: str) -> list[dict]:
    """One entry per reference file found in `directory`."""
    if not directory.is_dir():
        return []
    entries = []
    for path in sorted(directory.glob("*.md")):
        text = path.read_text(errors="replace")
        stamp = _GENERATED_ON.search(text)
        volumes = [int(n) for n in _VOLUME_ROW.findall(text)]
        entries.append({
            "module": path.stem,
            "source": source,
            "generated": stamp.group(1) if stamp else None,
            "records": sum(volumes) if volumes else None,
            "path": str(path),
        })
    return entries


_redirect_references()
